version: "3.5"

services:
  seeker:
    build:
      context: ./
    restart: always
    environment:
      - VIRTUAL_HOST=sogo.cloudns.ch
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=sogo.cloudns.ch
      - LETSENCRYPT_EMAIL=lilong@chainbow.io

networks:
  default:
    name: shared
    external: true
