version: "3.5"

services:
  seeker:
    image: thewhiteh4t/seeker
    restart: always
    environment:
      - REDIRECT=资料.pdf
      - TEMPLATE=1
      - VIRTUAL_HOST=sogo.cloudns.ch
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=sogo.cloudns.ch
      - LETSENCRYPT_EMAIL=lilong@chainbow.io
    volumes:
      - ./:/root/seeker
    ports:
      - "8080:8080"

networks:
  default:
    name: shared
    external: true
